"""Loading and validating the declared scenario suite.

The suite is the second input to the coverage diff, so its integrity matters as much as
the transcripts'. An unknown `expectation.type` is a hard error rather than a skipped
warning: a typo would otherwise produce a scenario that asserts nothing and passes forever.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal

import yaml
from pydantic import BaseModel, Field, ValidationError

from .errors import SuiteError

# Assertion types the graders can evaluate. Adding one without a grader fails the
# import-time check in graders.py.
ExpectationType = Literal[
    "tool_called",
    "verify_before_disclosure",
    "no_amount_disclosed",
    "no_pii_disclosed",
    "outcome_in",
    "max_turns",
    "agent_must_ask_for",
    "must_not_say",
    "no_repeated_agent_turn",
    "must_respond_in_caller_language",
    "must_escalate",
]


class Expectation(BaseModel):
    type: ExpectationType
    tool: str | None = None
    values: list[str] | None = None
    value: int | None = None
    pattern: str | None = None
    patterns: list[str] | None = None
    reason: str | None = None

    model_config = {"extra": "forbid"}   # a stray key is a typo and must fail loudly


class Persona(BaseModel):
    role: str = "borrower"
    temperament: str = "neutral"
    model_config = {"extra": "allow"}    # personas are open-ended


class Scenario(BaseModel):
    id: str
    name: str
    situation: str                       # the join key against production clusters
    description: str = ""
    owner: str = "unassigned"
    priority: str = "P2"
    language: str = "hi-IN"
    persona: Persona = Field(default_factory=Persona)
    opening_utterance: str = ""
    conditions: list[str] = Field(default_factory=list)
    expectations: list[Expectation] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    generated_from_cluster: str | None = None   # set for generated scenarios

    model_config = {"extra": "forbid"}


class Suite(BaseModel):
    scenarios: list[Scenario] = Field(default_factory=list)
    path: Path | None = None

    model_config = {"arbitrary_types_allowed": True}

    @property
    def situations(self) -> set[str]:
        return {s.situation for s in self.scenarios}

    def by_situation(self, situation: str) -> list[Scenario]:
        return [s for s in self.scenarios if s.situation == situation]

    def __len__(self) -> int:
        return len(self.scenarios)


def load_suite(directory: Path) -> Suite:
    """Load every *.yaml in `directory` as a scenario.

    Errors name the file and the offending field.
    """
    directory = Path(directory)
    if not directory.is_dir():
        raise SuiteError(f"suite directory does not exist: {directory}")

    scenarios: list[Scenario] = []
    seen_ids: dict[str, Path] = {}

    for f in sorted(directory.glob("*.yaml")) + sorted(directory.glob("*.yml")):
        try:
            raw = yaml.safe_load(f.read_text(encoding="utf-8"))
        except yaml.YAMLError as exc:
            raise SuiteError(f"{f.name}: not valid YAML", context={"error": str(exc)[:300]}) from exc
        if not isinstance(raw, dict):
            raise SuiteError(f"{f.name}: expected a mapping at the top level, got {type(raw).__name__}")
        try:
            sc = Scenario.model_validate(raw)
        except ValidationError as exc:
            first = exc.errors()[0]
            loc = ".".join(str(p) for p in first["loc"])
            raise SuiteError(f"{f.name}: invalid scenario at '{loc}': {first['msg']}") from exc

        if sc.id in seen_ids:
            raise SuiteError(
                f"{f.name}: duplicate scenario id {sc.id!r}, already declared in "
                f"{seen_ids[sc.id].name}"
            )
        seen_ids[sc.id] = f
        scenarios.append(sc)

    if not scenarios:
        raise SuiteError(f"no scenario files found in {directory}")
    return Suite(scenarios=scenarios, path=directory)


def write_scenario(scenario: Scenario, directory: Path) -> Path:
    """Write a scenario to the suite directory as YAML.

    An ordinary file, so a generated scenario goes through normal review.
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    slug = scenario.situation.replace("/", "_")
    path = directory / f"gen_{slug}.yaml"
    body: dict[str, Any] = scenario.model_dump(exclude_none=True, exclude_defaults=False)
    body.pop("generated_from_cluster", None)
    body["generated_from_cluster"] = scenario.generated_from_cluster
    header = (
        "# GENERATED by AgentTrace from an uncovered production cluster.\n"
        "# Review before merging: check the expectations encode what SHOULD happen,\n"
        "# not merely what the agent currently does.\n"
    )
    path.write_text(header + yaml.safe_dump(body, sort_keys=False, allow_unicode=True),
                    encoding="utf-8")
    return path
